apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony
  labels:
    name: harmony
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harmony
  template:
    metadata:
      labels:
        name: harmony
    spec:
      containers:
        - name: harmony
          imagePullPolicy: IfNotPresent
          image: harmonyservices/harmony:latest
          command:
            - "/harmony/bin/start-harmony-in-container"
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          ports:
            - containerPort: 3000
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: harmony
spec:
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: backend
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    name: harmony
  type: LoadBalancer