# Url to access prometheus
prometheus:
  url: http://prometheus.monitoring
  port: 9090

# Rules for custom metrics
rules:
  custom:
  - seriesQuery: 'num_ready_work_items{kubernetes_namespace!="",kubernetes_pod_name!=""}'
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
        name: {group: "apps", resource: "deployment"}
    name:
      matches: "num_ready_work_items"
      as: "num_ready_work_items"
    metricsQuery: '<<.Series>>{<<.LabelMatchers>>}'
